### ISSUE TITLE
Feature Request: Loading log file to populate UI

### ISSUE THREAD

**Issue by theelefant** [MoonRide303/Fooocus#3] opened 2023-08-16 22:47 UTC
Given that we now have a log file, wouldn't it be nice to populate the UI directly from that file?

**Comment by barepixels** [comment] 2023-08-16 23:21
Log files have a list of generated inages.  How would it knows which one you want to load.  Better would be load a specific PNG with metada

**Comment by MoonRide303** [comment] 2023-08-16 23:23
@theelefant log file is feature added by original Fooocus author and he mentioned still working on it. But temporary HTML file aren't really most convenient way for loading prompt from them, so I don't think this log file will be used like that.

I like the general idea, though, so (when I'll have some spare time) I will look into ComfyUI and try figuring out how loading settings from PNG / JSON files is done there (as well as restoring previous session state). But Comfy uses different UI framework, and it might not so trivial to port this functionality to Fooocus - so no promises.

**Comment by theelefant** [comment] 2023-08-16 23:28
> Log files have a list of generated inages. How would it knows which one you want to load. Better would be load a specific PNG with metada
 @barepixels I was referring to the JSON log introduced by this repository and not the HTML one from the original repository.

**Comment by That-Dude** [comment] 2023-08-17 06:59
It would be convenient to just drag a PNG generated with your fork into the GUI and have it populated, that's the expected behaviour from the current userbase.

**Comment by barepixels** [comment] 2023-08-17 14:36
vote

**Comment by MoonRide303** [comment] 2023-08-17 15:18
@barepixels I have initial version of loading prompt parameters from both JSON and PNG files working - should be ready to use today or tomorrow.

**Comment by barepixels** [comment] 2023-08-17 15:20
Dude, you are my hero

**Comment by MoonRide303** [comment] 2023-08-17 16:02
Just merged into moonride-main. It should work on metadata saved by current version, but might not be compatible with images generated with older versions. Let me know if it works for you.

**Comment by barepixels** [comment] 2023-08-17 16:12
Testing now.  Will report back soon

**Comment by barepixels** [comment] 2023-08-17 16:49
Am happy to report: Using "deference mode" in Photoshopshop.  The image generated before and image generated after loading PNG are exactly the same down to pixel level

**Comment by MoonRide303** [comment] 2023-08-17 17:23
@barepixels Settings like Saving metadata option, and numbe rof generated images is related to UI itself, not particular prompt / image. I agree it would be nice to have last UI settings automatically restored, but that's a bit different functionality. Btw. I found one bug, related to switch slider value loading - should be fixed now.

**Comment by barepixels** [comment] 2023-08-17 17:27
I will make a feature request at lllyasviel/Fooocus

**Comment by That-Dude** [comment] 2023-08-17 17:45
> @barepixels I have initial version of loading prompt parameters from both JSON and PNG files working - should be ready to use today or tomorrow.

You're on fire!

**Comment by That-Dude** [comment] 2023-08-17 17:54
> @barepixels Settings like Saving metadata option, and number of generated images are related to UI itself, not particular prompt / image. I agree it would be nice to have last UI settings automatically restored, but that's a bit different functionality. Btw. I found one bug, related to switch slider value loading - should be fixed now.

How about exposing 'save-metadata-on' as a command line switch. Or just default it to on. I think you're flying solo with that patch anyway.

**Comment by MoonRide303** [comment] 2023-08-17 18:05
@That-Dude Yeah, it could be useful feature - but I'd rather do it as extension for save/restore UI state made in vanilla Fooocus. Let's first give lllyasviel a chance to speak how he sees it, to avoid duplicating work.

**Comment by barepixels** [comment] 2023-08-17 20:22
Not wanting to RISK generating images without saving metadata to PNG, I have hard code in Fooocus-MoonRide/webui.py

save_metadata = gr.Radio(label='Save Metadata', choices=['Disabled', 'JSON', 'PNG'], value='PNG')

While at the same file (webui.py) I change the default "Image Number" from 2 to 1

image_number = gr.Slider(label='Image Number', minimum=1, maximum=32, step=1, value=1)

Could not figure how to set "Advance" to default "Checked"

**Comment by MoonRide303** [comment] 2023-08-17 20:47
@barepixels If you want to use quick hack, you can change (in `webui.py`)
```
                advanced_checkbox = gr.Checkbox(label='Advanced', value=False, container=False)
        with gr.Column(scale=0.5, visible=False) as right_col:
```
to
```
                advanced_checkbox = gr.Checkbox(label='Advanced', value=True, container=False)
        with gr.Column(scale=0.5, visible=True) as right_col:
```

**Comment by barepixels** [comment] 2023-08-17 21:25
Brother, it works.  Thank you

**Comment by barepixels** [comment] 2023-08-17 21:37
May I suggest to add a link to this fork at the footer.  Or show me how.

![link to git hub](https://github.com/MoonRide303/Fooocus/assets/92839033/3ecdf6f8-b85b-4b5d-a2df-da2ac98cc118)

**Comment by theelefant** [comment] 2023-08-18 12:50
Could we consider adding a fourth option, "JASON+PNG", in the Advanced Tab?

**Comment by That-Dude** [comment] 2023-08-18 12:52
Jason who? 😀

But those options should probably be tickboxes rather than radio buttons.

**Comment by theelefant** [comment] 2023-08-18 12:56
Voorhees :)

But yes, radio buttons would be better.

**Comment by MoonRide303** [comment] 2023-08-18 13:43
Done & merged:
![image](https://github.com/MoonRide303/Fooocus/assets/130458190/94bafdc1-0c95-4f2e-85e1-b495ced8a7c6)

**Comment by That-Dude** [comment] 2023-08-18 14:09
> Done & merged: ![image](https://user-images.githubusercontent.com/130458190/261621785-94bafdc1-0c95-4f2e-85e1-b495ced8a7c6.png)

I'm concerned that you're not getting enough sleep Mr MoonRide :-)

**Comment by MoonRide303** [comment] 2023-08-18 14:40
@That-Dude Yeah, I could probably use some more of that :).

@barepixels You can check out latest version of moonride-main - I've added loading basic UI settings from JSON file (`settings.json`), it looks like that:
```{"advanced_mode": false, "image_number": 2, "save_metadata_json": false, "save_metadata_png": false}```
you can set your preferred values there, instead of having to edit the code.

**Comment by barepixels** [comment] 2023-08-18 15:42
TIP:  When load metadata from PNG one must make sure the "Random" check box is unchecked to insure the original seed is being used.

I suppose when choosing to load metadata from PNG "Random" checkbox should be automatically set as unchecked.  But this is not a high priority for me.

**Comment by MoonRide303** [comment] 2023-08-18 16:05
@barepixels Goot catch - I just corrected this random seed checkbox - should automatically untick now after loading prompt files (either PNG or JSON) that include seed value. Sample settings file is provided under different name is to avoid conflicts with changes coming from git to that file (which would happen if settings.json was edited locally by you, and then I would add some more fields to it, etc.).

Seems to be working pretty fine now, overall, so... I am closing it :).

**Closed** 2023-08-18 16:07 UTC
